INSERT INTO vehicles (make, model, year, trim_level, vehicle_type, gcc_spec, chinese_spec, range_km, battery_kwh, price, manufacturer_direct_price, grey_market_price, grey_market_source, grey_market_url, description, specs, images, stock_count, status)
VALUES ('Geely', 'Galaxy L7', 2025, 'PHEV', 'Hybrid', false, true, 115, 18.4, 190000, NULL, NULL, 'China import', NULL, 'Geely Galaxy L7 PHEV - Plug-in hybrid SUV competing with BYD Song Plus DM-i. Grey market only.', ''{"features": ["Plug-in hybrid SUV", "115km electric range", "1370km combined range", "Competitor to BYD Song Plus DM-i"], "range_km": 115, "battery_kwh": 18.4, "drivetrain": "FWD", "body_style": "SUV", "seats": 5}''::jsonb, ''[]''::jsonb, 1, 'pending');
INSERT INTO vehicles (make, model, year, trim_level, vehicle_type, gcc_spec, chinese_spec, range_km, battery_kwh, price, manufacturer_direct_price, grey_market_price, grey_market_source, grey_market_url, description, specs, images, stock_count, status)
VALUES ('Haval', 'H6', 2025, '2.0T Supreme', 'ICE', true, false, NULL, NULL, 89100, 90000, 89100, NULL, NULL, 'Haval H6 2.0T Supreme - Mid-size SUV with 2.0L turbo engine, officially available in Qatar through GWM.', ''{"engine": {"displacement_l": 2.0, "power_hp": 201, "torque_nm": 320}, "dimensions": {"length_mm": 4653, "width_mm": 1886, "height_mm": 1724, "wheelbase_mm": 2738}, "features": ["2.0L turbocharged engine", "201 HP", "Official GCC specs", "Advanced safety features"], "drivetrain": "FWD", "body_style": "SUV", "seats": 5}''::jsonb, ''[{"url": "https://gwmqatar.com/haval-h6-2025/", "type": "exterior", "is_primary": true}]''::jsonb, 1, 'pending');
INSERT INTO vehicles (make, model, year, trim_level, vehicle_type, gcc_spec, chinese_spec, range_km, battery_kwh, price, manufacturer_direct_price, grey_market_price, grey_market_source, grey_market_url, description, specs, images, stock_count, status)
VALUES ('Haval', 'H6', 2025, '2.0T Premium 4WD', 'ICE', true, false, NULL, NULL, 103950, 105000, 103950, NULL, NULL, 'Haval H6 2.0T Premium 4WD - Top-spec version with 4WD system.', ''{"features": ["2.0L turbocharged engine", "4WD system", "Premium trim", "Advanced safety features"], "drivetrain": "4WD", "body_style": "SUV", "seats": 5}''::jsonb, ''[]''::jsonb, 1, 'pending');
INSERT INTO vehicles (make, model, year, trim_level, vehicle_type, gcc_spec, chinese_spec, range_km, battery_kwh, price, manufacturer_direct_price, grey_market_price, grey_market_source, grey_market_url, description, specs, images, stock_count, status)
VALUES ('Haval', 'H6', 2025, 'Hybrid', 'Hybrid', false, true, NULL, NULL, 113751, NULL, 113751, 'UAE import via QatarSale', NULL, 'Haval H6 Hybrid - Hybrid version available in UAE, can be imported to Qatar through grey market.', ''{"features": ["Hybrid powertrain", "Better fuel economy", "Available in UAE", "Grey market import to Qatar"], "drivetrain": "FWD", "body_style": "SUV"}''::jsonb, ''[]''::jsonb, 1, 'pending');
INSERT INTO vehicles (make, model, year, trim_level, vehicle_type, gcc_spec, chinese_spec, range_km, battery_kwh, price, manufacturer_direct_price, grey_market_price, grey_market_source, grey_market_url, description, specs, images, stock_count, status)
VALUES ('GWM', 'ORA 03', 2026, '48 kWh Pro', 'EV', true, false, 420, 48, 95000, 95000, NULL, NULL, NULL, 'GWM ORA 03 Pro - Retro-styled electric hatchback with 420km range. Officially available in Qatar.', ''{"dimensions": {"length_mm": 4235, "width_mm": 1825, "height_mm": 1596, "wheelbase_mm": 2650}, "battery": {"type": "Lithium-ion", "capacity_kwh": 48, "range_km": 420}, "charging": {"dc_charging_kw": 80, "ac_charging_kw": 6.6, "charging_time_10_80_min": 45}, "features": ["Retro-modern design", "420km WLTP range", "Fast charging support", "Women-friendly features"], "range_km": 420, "battery_kwh": 48, "acceleration_0_100": 7.9, "top_speed_kmh": 152, "power_kw": 126, "power_hp": 169, "drivetrain": "FWD", "body_style": "Hatchback", "seats": 5}''::jsonb, ''[{"url": "https://gwmqatar.com/ora-electric-car/", "type": "exterior", "is_primary": true}]''::jsonb, 1, 'pending');
INSERT INTO vehicles (make, model, year, trim_level, vehicle_type, gcc_spec, chinese_spec, range_km, battery_kwh, price, manufacturer_direct_price, grey_market_price, grey_market_source, grey_market_url, description, specs, images, stock_count, status)
VALUES ('NETA', 'V', 2023, 'Standard', 'EV', false, true, 401, 38.5, 65586, NULL, 65586, 'UAE import (limited availability)', NULL, 'NETA V - Compact electric SUV from Hozon Auto. NOTE: NETA Motors has halted production, raising concerns about warranty and spare parts support in the GCC. Limited availability in UAE.', ''{"dimensions": {"length_mm": 4070, "width_mm": 1690, "height_mm": 1540, "wheelbase_mm": 2420}, "battery": {"type": "Lithium-ion", "capacity_kwh": 38.5, "range_km": 401}, "features": ["Compact electric SUV", "401km NEDC range", "Affordable pricing", "Production halted - warranty concerns"], "range_km": 401, "battery_kwh": 38.5, "top_speed_kmh": 101, "power_kw": 70, "power_hp": 95, "drivetrain": "FWD", "body_style": "Compact SUV", "seats": 5}''::jsonb, ''[]''::jsonb, 1, 'pending');
INSERT INTO vehicles (make, model, year, trim_level, vehicle_type, gcc_spec, chinese_spec, range_km, battery_kwh, price, manufacturer_direct_price, grey_market_price, grey_market_source, grey_market_url, description, specs, images, stock_count, status)
VALUES ('NETA', 'U', 2023, '54.34 kWh', 'EV', false, true, 500, 54.34, 75000, NULL, NULL, 'China import', NULL, 'NETA U 54.34 kWh - Larger electric SUV. WARNING: Production halted due to manufacturer financial issues.', ''{"features": ["54.34 kWh battery", "500km range", "Grey market import", "Production halted - warranty concerns"], "range_km": 500, "battery_kwh": 54.34, "drivetrain": "FWD", "body_style": "SUV", "seats": 5}''::jsonb, ''[]''::jsonb, 1, 'pending');
INSERT INTO vehicles (make, model, year, trim_level, vehicle_type, gcc_spec, chinese_spec, range_km, battery_kwh, price, manufacturer_direct_price, grey_market_price, grey_market_source, grey_market_url, description, specs, images, stock_count, status)
VALUES ('Voyah', 'FREE', 2025, '106 kWh Extended Range', 'EV', true, false, 680, 106, 230000, 230000, NULL, NULL, NULL, 'Voyah FREE 106 kWh - Premium electric SUV from Dongfeng with 680km range, 490HP dual motor, luxury features. Officially available in Qatar.', ''{"dimensions": {"length_mm": 4905, "width_mm": 1950, "height_mm": 1645, "wheelbase_mm": 2960}, "battery": {"type": "Lithium-ion NCM", "capacity_kwh": 106, "range_km": 680}, "charging": {"dc_charging_kw": 120, "ac_charging_kw": 11, "charging_time_30_80_min": 36}, "features": ["Dongfeng premium EV brand", "680km range", "4.2s 0-100 km/h", "490 HP dual motor", "Luxury interior", "Air suspension", "Official Qatar distributor"], "range_km": 680, "battery_kwh": 106, "acceleration_0_100": 4.2, "top_speed_kmh": 200, "power_kw": 360, "power_hp": 490, "drivetrain": "AWD", "body_style": "SUV", "seats": 5}''::jsonb, ''[{"url": "https://voyahqatar.com/voyah-free/", "type": "exterior", "is_primary": true}]''::jsonb, 1, 'pending');
INSERT INTO vehicles (make, model, year, trim_level, vehicle_type, gcc_spec, chinese_spec, range_km, battery_kwh, price, manufacturer_direct_price, grey_market_price, grey_market_source, grey_market_url, description, specs, images, stock_count, status)
VALUES ('Voyah', 'FREE', 2025, 'REEV Range Extender', 'Hybrid', false, true, 200, 43, 84150, NULL, 84150, 'UAE import via QatarSale', NULL, 'Voyah FREE REEV - Range extender version with 1357km combined range. Available through UAE imports.', ''{"features": ["Range extender hybrid", "1357km total range", "200km electric range", "43 kWh battery", "Premium Dongfeng brand"], "range_km": 200, "battery_kwh": 43, "acceleration_0_100": 4.5, "top_speed_kmh": 200, "power_kw": 360, "power_hp": 490, "drivetrain": "AWD", "body_style": "SUV", "seats": 5}''::jsonb, ''[]''::jsonb, 1, 'pending');
INSERT INTO vehicles (make, model, year, trim_level, vehicle_type, gcc_spec, chinese_spec, range_km, battery_kwh, price, manufacturer_direct_price, grey_market_price, grey_market_source, grey_market_url, description, specs, images, stock_count, status)
VALUES ('Avatr', '11', 2025, 'Ultra Range AWD', 'EV', true, false, 680, 90, 320000, 320000, NULL, NULL, NULL, 'Avatr 11 Ultra Range AWD - Premium electric SUV with Huawei technology, 680km range, triple LiDAR, 240kW charging. Officially available in Qatar through Elaf Auto.', ''{"dimensions": {"length_mm": 4880, "width_mm": 1970, "height_mm": 1601, "wheelbase_mm": 2975}, "battery": {"type": "Lithium-ion NCM", "capacity_kwh": 90, "range_km": 680, "technology": "CATL NCM"}, "charging": {"dc_charging_kw": 240, "ac_charging_kw": 11, "charging_time_10_80_min": 25}, "features": ["Huawei-powered technology", "680km range", "240kW ultra-fast charging", "Triple LiDAR sensors", "AI cockpit", "578 HP dual motor", "3.9s 0-100 km/h", "Air suspension", "Official Qatar distributor (Elaf Auto)"], "range_km": 680, "battery_kwh": 90, "acceleration_0_100": 3.9, "top_speed_kmh": 200, "power_kw": 425, "power_hp": 578, "drivetrain": "AWD", "body_style": "SUV", "seats": 5}''::jsonb, ''[{"url": "https://www.avatrqa.com/avatr11", "type": "exterior", "is_primary": true}]''::jsonb, 1, 'pending');
