INSERT INTO vehicles (make, model, year, trim_level, vehicle_type, gcc_spec, chinese_spec, range_km, battery_kwh, price, manufacturer_direct_price, grey_market_price, grey_market_source, grey_market_url, description, specs, images, stock_count, status)
VALUES ('Chery', 'eQ7', 2025, 'Base', 'EV', false, true, 412, 53.87, 85000, NULL, 85000, 'Grey Market / China Import', NULL, 'Chery eQ7 Base - 412km range with 53.87kWh battery. Grey market import.', ''{"dimensions": {"length_mm": 4675, "width_mm": 1865, "height_mm": 1680, "wheelbase_mm": 2715}, "battery": {"type": "Lithium Iron Phosphate (LFP)", "capacity_kwh": 53.87}, "range_km": 412, "battery_kwh": 53.87, "acceleration_0_100": 9.5, "top_speed_kmh": 160, "power_kw": 150, "power_hp": 201, "drivetrain": "FWD", "body_style": "SUV", "seats": 5}''::jsonb, ''[]''::jsonb, 1, 'pending');
INSERT INTO vehicles (make, model, year, trim_level, vehicle_type, gcc_spec, chinese_spec, range_km, battery_kwh, price, manufacturer_direct_price, grey_market_price, grey_market_source, grey_market_url, description, specs, images, stock_count, status)
VALUES ('Chery', 'TIGGO 8 PRO e+', 2025, 'PHEV', 'Hybrid', true, false, 75, 19.27, 139000, 139000, NULL, NULL, NULL, 'Chery Tiggo 8 Pro e+ - Plug-in hybrid SUV with 75km electric range and 1000km combined range. Official GCC spec available via Elite Motors.', ''{"dimensions": {"length_mm": 4722, "width_mm": 1860, "height_mm": 1745, "wheelbase_mm": 2710}, "battery": {"type": "Lithium-ion", "capacity_kwh": 19.27, "pure_electric_range": 75}, "features": ["1.5TCI Turbocharged Engine", "24.6-inch Dual Screen", "9 Driving Modes", "Pure electric endurance of 75km"], "range_km": 75, "battery_kwh": 19.27, "acceleration_0_100": 8.2, "top_speed_kmh": 185, "power_kw": 240, "power_hp": 326, "drivetrain": "AWD", "body_style": "SUV", "seats": 5}''::jsonb, ''[{"url": "https://cheryqatar.com/sites/default/files/2023-02/TE1.jpg", "type": "exterior", "is_primary": true}]''::jsonb, 1, 'pending');
INSERT INTO vehicles (make, model, year, trim_level, vehicle_type, gcc_spec, chinese_spec, range_km, battery_kwh, price, manufacturer_direct_price, grey_market_price, grey_market_source, grey_market_url, description, specs, images, stock_count, status)
VALUES ('Chery', 'ARRIZO 8', 2025, 'Luxury', 'ICE', true, false, NULL, NULL, 91000, 91000, 63900, 'QatarSale', NULL, 'Chery Arrizo 8 - Premium sedan with 24.6-inch dual screen, 1.6L turbo engine. Official GCC spec available.', ''{"dimensions": {"length_mm": 4780, "width_mm": 1843, "height_mm": 1469, "wheelbase_mm": 2790}, "engine": {"type": "1.6L Turbo", "power_hp": 197, "torque_nm": 290}, "features": ["24.6-inch Floating Dual Screen", "Lion 5.0 AI Technology", "10 Airbags"], "drivetrain": "FWD", "body_style": "Sedan", "seats": 5}''::jsonb, ''[{"url": "https://cheryqatar.com/sites/default/files/2023-05/M1E_Appearance_Front%20Right_20221204.jpg", "type": "exterior_front", "is_primary": true}]''::jsonb, 1, 'pending');
INSERT INTO vehicles (make, model, year, trim_level, vehicle_type, gcc_spec, chinese_spec, range_km, battery_kwh, price, manufacturer_direct_price, grey_market_price, grey_market_source, grey_market_url, description, specs, images, stock_count, status)
VALUES ('Chery', 'QQ ICE CREAM', 2024, 'Standard', 'EV', false, true, 170, 13.9, 45000, NULL, 45000, 'Grey Market / China Import', NULL, 'Chery QQ Ice Cream - Small urban EV with 170km range. Grey market import from China.', ''{"dimensions": {"length_mm": 3010, "width_mm": 1500, "height_mm": 1640, "wheelbase_mm": 1960}, "battery": {"type": "Lithium Iron Phosphate (LFP)", "capacity_kwh": 13.9}, "features": ["Urban Micro EV", "120-170km Range", "27 hp Electric Motor"], "range_km": 170, "battery_kwh": 13.9, "top_speed_kmh": 100, "power_kw": 20, "power_hp": 27, "drivetrain": "FWD", "body_style": "Hatchback", "seats": 4}''::jsonb, ''[]''::jsonb, 1, 'pending');
INSERT INTO vehicles (make, model, year, trim_level, vehicle_type, gcc_spec, chinese_spec, range_km, battery_kwh, price, manufacturer_direct_price, grey_market_price, grey_market_source, grey_market_url, description, specs, images, stock_count, status)
VALUES ('Chery', 'QQ ICE CREAM', 2024, 'Base', 'EV', false, true, 120, 9.42, 40000, NULL, 40000, 'Grey Market / China Import', NULL, 'Chery QQ Ice Cream Base - 120km range with 9.42kWh battery. Grey market import.', ''{"dimensions": {"length_mm": 3010, "width_mm": 1500, "height_mm": 1640, "wheelbase_mm": 1960}, "battery": {"type": "Lithium Iron Phosphate (LFP)", "capacity_kwh": 9.42}, "range_km": 120, "battery_kwh": 9.42, "top_speed_kmh": 100, "power_kw": 20, "power_hp": 27, "drivetrain": "FWD", "body_style": "Hatchback", "seats": 4}''::jsonb, ''[]''::jsonb, 1, 'pending');
INSERT INTO vehicles (make, model, year, trim_level, vehicle_type, gcc_spec, chinese_spec, range_km, battery_kwh, price, manufacturer_direct_price, grey_market_price, grey_market_source, grey_market_url, description, specs, images, stock_count, status)
VALUES ('Jaecoo', 'J7', 2025, 'Summit PHEV', 'Hybrid', true, false, 80, 18.3, 95000, 95000, NULL, NULL, NULL, 'Jaecoo J7 Summit PHEV - Plug-in hybrid SUV officially launched by Silver Lake Motors Qatar. 1.6L turbo with electric motor.', ''{"dimensions": {"length_mm": 4500, "width_mm": 1865, "height_mm": 1680, "wheelbase_mm": 2672}, "engine": {"type": "1.6L Turbocharged PHEV", "fuel_economy": "16.7 km/l"}, "features": ["Plug-in Hybrid System", "200mm Ground Clearance", "Dual Zone Climate Control"], "range_km": 80, "battery_kwh": 18.3, "acceleration_0_100": 7.5, "top_speed_kmh": 200, "power_kw": 185, "power_hp": 251, "drivetrain": "AWD", "body_style": "SUV", "seats": 5}''::jsonb, ''[]''::jsonb, 1, 'pending');
INSERT INTO vehicles (make, model, year, trim_level, vehicle_type, gcc_spec, chinese_spec, range_km, battery_kwh, price, manufacturer_direct_price, grey_market_price, grey_market_source, grey_market_url, description, specs, images, stock_count, status)
VALUES ('Jaecoo', 'J7', 2025, 'EX+ AWD', 'Hybrid', true, false, NULL, NULL, 89000, 89000, NULL, NULL, NULL, 'Jaecoo J7 EX+ AWD - Turbocharged petrol SUV with AWD. Official GCC spec.', ''{"dimensions": {"length_mm": 4500, "width_mm": 1865, "height_mm": 1680, "wheelbase_mm": 2672}, "engine": {"type": "1.6L Turbocharged", "power_hp": 185, "torque_nm": 290}, "fuel_economy": "12.8 km/l", "drivetrain": "AWD", "body_style": "SUV", "seats": 5}''::jsonb, ''[]''::jsonb, 1, 'pending');
INSERT INTO vehicles (make, model, year, trim_level, vehicle_type, gcc_spec, chinese_spec, range_km, battery_kwh, price, manufacturer_direct_price, grey_market_price, grey_market_source, grey_market_url, description, specs, images, stock_count, status)
VALUES ('Jaecoo', 'J7', 2025, 'FWD', 'ICE', true, false, NULL, NULL, 79900, 79900, NULL, NULL, NULL, 'Jaecoo J7 FWD - Entry-level turbocharged SUV with FWD.', ''{"engine": {"type": "1.6L Turbocharged", "fuel_economy": "14.3 km/l"}, "drivetrain": "FWD", "body_style": "SUV", "seats": 5}''::jsonb, ''[]''::jsonb, 1, 'pending');
INSERT INTO vehicles (make, model, year, trim_level, vehicle_type, gcc_spec, chinese_spec, range_km, battery_kwh, price, manufacturer_direct_price, grey_market_price, grey_market_source, grey_market_url, description, specs, images, stock_count, status)
VALUES ('Jaecoo', 'J5', 2025, 'Premium', 'Hybrid', true, false, NULL, NULL, 80000, 80000, NULL, NULL, NULL, 'Jaecoo J5 Premium - Compact hybrid SUV with excellent cargo capacity. Official GCC spec from Silver Lake Motors.', ''{"dimensions": {"length_mm": 4350, "width_mm": 1820, "height_mm": 1655, "wheelbase_mm": 2630}, "cargo_space_liters": 480, "cargo_space_expanded": 1180, "features": ["480L Boot Space", "Expandable to 1,180L", "Compact SUV"], "drivetrain": "FWD", "body_style": "SUV", "seats": 5}''::jsonb, ''[]''::jsonb, 1, 'pending');
INSERT INTO vehicles (make, model, year, trim_level, vehicle_type, gcc_spec, chinese_spec, range_km, battery_kwh, price, manufacturer_direct_price, grey_market_price, grey_market_source, grey_market_url, description, specs, images, stock_count, status)
VALUES ('Jaecoo', 'J8', 2025, 'Flagship', 'ICE', true, false, NULL, NULL, 110000, 110000, NULL, NULL, NULL, 'Jaecoo J8 Flagship - Premium SUV officially launched by Silver Lake Motors Qatar.', ''{"features": ["Built on Strong Chassis", "Stability and Confidence", "Premium Flagship SUV"], "drivetrain": "AWD", "body_style": "SUV", "seats": 5}''::jsonb, ''[]''::jsonb, 1, 'pending');
