INSERT INTO vehicles (make, model, year, trim_level, vehicle_type, gcc_spec, chinese_spec, range_km, battery_kwh, price, manufacturer_direct_price, grey_market_price, grey_market_source, grey_market_url, description, specs, images, stock_count, status)
VALUES ('Chery', 'TIGGO 4 PRO', 2025, 'Standard', 'ICE', true, false, NULL, NULL, 54500, 54500, NULL, NULL, NULL, 'Chery Tiggo 4 Pro - Subcompact SUV with 1.5L turbo engine.', ''{"engine": {"type": "1.5L Turbocharged", "power_hp": 156}, "drivetrain": "FWD", "body_style": "SUV", "seats": 5}''::jsonb, ''[{"url": "https://cheryqatar.com/sites/default/files/2023-02/1.5T-image%204%20copy.jpg", "type": "exterior", "is_primary": true}]''::jsonb, 1, 'pending');
INSERT INTO vehicles (make, model, year, trim_level, vehicle_type, gcc_spec, chinese_spec, range_km, battery_kwh, price, manufacturer_direct_price, grey_market_price, grey_market_source, grey_market_url, description, specs, images, stock_count, status)
VALUES ('Chery', 'ARRIZO 6 PRO', 2025, 'Standard', 'ICE', true, false, NULL, NULL, 53000, 53000, NULL, NULL, NULL, 'Chery Arrizo 6 Pro - Compact sedan with 1.6L engine.', ''{"engine": {"type": "1.6L Naturally Aspirated", "power_hp": 126}, "drivetrain": "FWD", "body_style": "Sedan", "seats": 5}''::jsonb, ''[{"url": "https://cheryqatar.com/sites/default/files/2023-02/Arrizo%206%20pro.jpg", "type": "exterior", "is_primary": true}]''::jsonb, 1, 'pending');
INSERT INTO vehicles (make, model, year, trim_level, vehicle_type, gcc_spec, chinese_spec, range_km, battery_kwh, price, manufacturer_direct_price, grey_market_price, grey_market_source, grey_market_url, description, specs, images, stock_count, status)
VALUES ('Chery', 'ARRIZO 5', 2025, 'Standard', 'ICE', true, false, NULL, NULL, 61000, 61000, NULL, NULL, NULL, 'Chery Arrizo 5 - Subcompact sedan with 1.5L turbo engine.', ''{"engine": {"type": "1.5L Turbocharged", "power_hp": 147}, "drivetrain": "FWD", "body_style": "Sedan", "seats": 5}''::jsonb, ''[{"url": "https://cheryqatar.com/sites/default/files/2023-05/WEB%20AR5%202.png", "type": "exterior", "is_primary": true}]''::jsonb, 1, 'pending');
INSERT INTO vehicles (make, model, year, trim_level, vehicle_type, gcc_spec, chinese_spec, range_km, battery_kwh, price, manufacturer_direct_price, grey_market_price, grey_market_source, grey_market_url, description, specs, images, stock_count, status)
VALUES ('MG', 'ZS EV', 2025, 'Long Range', 'EV', true, false, 440, 72.6, 144764, 144764, NULL, NULL, NULL, 'MG ZS EV Long Range - Affordable electric SUV with 440km range, 72.6kWh LFP battery, and competitive pricing.', ''{"dimensions": {"length_mm": 4323, "width_mm": 1809, "height_mm": 1644, "wheelbase_mm": 2585}, "battery": {"type": "Lithium Iron Phosphate (LFP)", "capacity_kwh": 72.6, "usable_kwh": 68.3, "warranty": "8 years"}, "charging": {"dc_charging_kw": 87, "ac_charging_kw": 6.6, "charging_time_10_80_min_dc": 42}, "features": ["72.6 kWh LFP battery", "440 km WLTP range", "MG Pilot driver assistance", "360-degree camera", "PM2.5 air filtration"], "range_km": 440, "battery_kwh": 72.6, "acceleration_0_100": 8.4, "top_speed_kmh": 160, "power_kw": 130, "power_hp": 176, "drivetrain": "FWD", "body_style": "SUV", "seats": 5}''::jsonb, ''[{"url": "https://www.mg-qa.com/new-cars/mg-zs-ev", "type": "exterior", "is_primary": true}]''::jsonb, 1, 'pending');
INSERT INTO vehicles (make, model, year, trim_level, vehicle_type, gcc_spec, chinese_spec, range_km, battery_kwh, price, manufacturer_direct_price, grey_market_price, grey_market_source, grey_market_url, description, specs, images, stock_count, status)
VALUES ('MG', 'MG 4 EV', 2025, 'Standard Range 51 kWh', 'EV', true, false, 365, 51, 100900, 100900, NULL, NULL, NULL, 'MG 4 EV Standard Range - Rear-wheel drive electric hatchback with 365km range.', ''{"dimensions": {"length_mm": 4287, "width_mm": 1836, "height_mm": 1506, "wheelbase_mm": 2705}, "battery": {"type": "Lithium Iron Phosphate (LFP)", "capacity_kwh": 51, "technology": "Modular Scalable Platform (MSP)"}, "charging": {"dc_charging_kw": 88, "ac_charging_kw": 11}, "features": ["Rear-wheel drive", "5-link rear suspension", "Vehicle-to-load (V2L)", "MG iSMART connectivity"], "range_km": 365, "battery_kwh": 51, "acceleration_0_100": 7.9, "top_speed_kmh": 160, "power_kw": 125, "power_hp": 170, "drivetrain": "RWD", "body_style": "Hatchback", "seats": 5}''::jsonb, ''[]''::jsonb, 1, 'pending');
INSERT INTO vehicles (make, model, year, trim_level, vehicle_type, gcc_spec, chinese_spec, range_km, battery_kwh, price, manufacturer_direct_price, grey_market_price, grey_market_source, grey_market_url, description, specs, images, stock_count, status)
VALUES ('MG', 'MG 4 EV', 2025, 'Long Range 64 kWh', 'EV', true, false, 465, 64, 107000, 107000, NULL, NULL, NULL, 'MG 4 EV Long Range 64 kWh with 465km range and 140kW DC charging.', ''{"battery": {"capacity_kwh": 64}, "charging": {"dc_charging_kw": 140}, "range_km": 465, "battery_kwh": 64, "acceleration_0_100": 7.5, "top_speed_kmh": 160, "power_kw": 150, "power_hp": 204, "drivetrain": "RWD", "body_style": "Hatchback", "seats": 5}''::jsonb, ''[]''::jsonb, 1, 'pending');
INSERT INTO vehicles (make, model, year, trim_level, vehicle_type, gcc_spec, chinese_spec, range_km, battery_kwh, price, manufacturer_direct_price, grey_market_price, grey_market_source, grey_market_url, description, specs, images, stock_count, status)
VALUES ('MG', 'MG 4 EV', 2025, 'XPower 77 kWh', 'EV', false, true, 530, 77, 145000, NULL, 145000, 'QatarSale (estimated)', NULL, 'MG 4 EV XPower - High-performance dual-motor version with 435HP, 3.8s acceleration. Grey market import from UAE/China.', ''{"battery": {"capacity_kwh": 77}, "features": ["Dual motor AWD", "3.8s 0-100 km/h", "530km range", "Performance chassis tuning"], "range_km": 530, "battery_kwh": 77, "acceleration_0_100": 3.8, "top_speed_kmh": 200, "power_kw": 320, "power_hp": 435, "drivetrain": "AWD", "body_style": "Hatchback", "seats": 5}''::jsonb, ''[]''::jsonb, 1, 'pending');
INSERT INTO vehicles (make, model, year, trim_level, vehicle_type, gcc_spec, chinese_spec, range_km, battery_kwh, price, manufacturer_direct_price, grey_market_price, grey_market_source, grey_market_url, description, specs, images, stock_count, status)
VALUES ('MG', 'HS Hybrid+', 2025, 'Deluxe', 'Hybrid', true, false, 85, 16.6, 116316, 116316, NULL, NULL, NULL, 'MG HS Hybrid+ Deluxe - Plug-in hybrid SUV with 1287km combined range, 85km electric only.', ''{"dimensions": {"length_mm": 4579, "width_mm": 1876, "height_mm": 1685, "wheelbase_mm": 2720}, "battery": {"type": "Lithium-ion", "capacity_kwh": 16.6, "electric_range_km": 85}, "fuel_efficiency": {"combined_l_100km": 1.8, "combined_range_km": 1287}, "features": ["Plug-in hybrid system", "1287km combined range", "85km electric range", "MG Pilot driver assist"], "range_km": 85, "battery_kwh": 16.6, "acceleration_0_100": 7.9, "top_speed_kmh": 190, "power_kw": 186, "power_hp": 254, "drivetrain": "FWD", "body_style": "SUV", "seats": 5}''::jsonb, ''[]''::jsonb, 1, 'pending');
INSERT INTO vehicles (make, model, year, trim_level, vehicle_type, gcc_spec, chinese_spec, range_km, battery_kwh, price, manufacturer_direct_price, grey_market_price, grey_market_source, grey_market_url, description, specs, images, stock_count, status)
VALUES ('MG', 'HS Hybrid+', 2025, 'Luxury', 'Hybrid', true, false, 85, 16.6, 135728, 135728, NULL, NULL, NULL, 'MG HS Hybrid+ Luxury trim with premium features.', ''{"range_km": 85, "battery_kwh": 16.6, "drivetrain": "FWD", "body_style": "SUV"}''::jsonb, ''[]''::jsonb, 1, 'pending');
INSERT INTO vehicles (make, model, year, trim_level, vehicle_type, gcc_spec, chinese_spec, range_km, battery_kwh, price, manufacturer_direct_price, grey_market_price, grey_market_source, grey_market_url, description, specs, images, stock_count, status)
VALUES ('MG', 'EHS', 2025, 'PHEV', 'Hybrid', true, false, 75, 16.6, 135233, 135233, NULL, NULL, NULL, 'MG EHS PHEV - Plug-in hybrid SUV similar to HS Hybrid+ but different styling/marketing.', ''{"features": ["Plugin hybrid SUV", "75km electric range", "1200km total range"], "range_km": 75, "battery_kwh": 16.6, "drivetrain": "FWD", "body_style": "SUV"}''::jsonb, ''[]''::jsonb, 1, 'pending');
