INSERT INTO vehicles (make, model, year, trim_level, vehicle_type, gcc_spec, chinese_spec, range_km, battery_kwh, price, manufacturer_direct_price, grey_market_price, grey_market_source, grey_market_url, description, specs, images, stock_count, status)
VALUES ('BYD', 'SEAL 7 DM-i', 2025, 'AWD', 'Hybrid', true, false, 800, 17.6, 133714, 133714, NULL, NULL, NULL, 'BYD SEAL 7 DM-i AWD with 4.8s acceleration.', ''{"range_km": 800, "battery_kwh": 17.6, "acceleration_0_100": 4.8, "top_speed_kmh": 190, "power_kw": 270, "power_hp": 366, "drivetrain": "AWD", "body_style": "Sedan"}''::jsonb, ''[]''::jsonb, 1, 'pending');
INSERT INTO vehicles (make, model, year, trim_level, vehicle_type, gcc_spec, chinese_spec, range_km, battery_kwh, price, manufacturer_direct_price, grey_market_price, grey_market_source, grey_market_url, description, specs, images, stock_count, status)
VALUES ('BYD', 'SONG PLUS DM-i', 2025, 'FWD', 'Hybrid', true, false, 110, 18.3, 110648, 110648, NULL, NULL, NULL, 'BYD SONG PLUS DM-i - plug-in hybrid SUV with 890km combined range.', ''{"dimensions": {"length_mm": 4705, "width_mm": 1890, "height_mm": 1680, "wheelbase_mm": 2765}, "range_km": 110, "battery_kwh": 18.3, "acceleration_0_100": 7.3, "top_speed_kmh": 170, "power_kw": 150, "power_hp": 204, "drivetrain": "FWD", "body_style": "SUV"}''::jsonb, ''[]''::jsonb, 1, 'pending');
INSERT INTO vehicles (make, model, year, trim_level, vehicle_type, gcc_spec, chinese_spec, range_km, battery_kwh, price, manufacturer_direct_price, grey_market_price, grey_market_source, grey_market_url, description, specs, images, stock_count, status)
VALUES ('BYD', 'SONG PLUS EV', 2025, 'Standard', 'EV', true, false, 520, 71.8, 80000, 80000, NULL, NULL, NULL, 'BYD SONG PLUS EV - electric SUV with 520km range.', ''{"dimensions": {"length_mm": 4785, "width_mm": 1890, "height_mm": 1665, "wheelbase_mm": 2765}, "range_km": 520, "battery_kwh": 71.8, "acceleration_0_100": 7.5, "top_speed_kmh": 160, "power_kw": 150, "power_hp": 204, "drivetrain": "FWD", "body_style": "SUV"}''::jsonb, ''[]''::jsonb, 1, 'pending');
INSERT INTO vehicles (make, model, year, trim_level, vehicle_type, gcc_spec, chinese_spec, range_km, battery_kwh, price, manufacturer_direct_price, grey_market_price, grey_market_source, grey_market_url, description, specs, images, stock_count, status)
VALUES ('BYD', 'QIN PLUS DM-i', 2025, 'Standard', 'Hybrid', true, false, 90, 18.3, 74278, 74278, NULL, NULL, NULL, 'BYD QIN PLUS DM-i - efficient plug-in hybrid sedan with 795km range.', ''{"dimensions": {"length_mm": 4765, "width_mm": 1837, "height_mm": 1495, "wheelbase_mm": 2718}, "range_km": 90, "battery_kwh": 18.3, "acceleration_0_100": 7.3, "top_speed_kmh": 185, "power_kw": 197, "power_hp": 266, "drivetrain": "FWD", "body_style": "Sedan"}''::jsonb, ''[]''::jsonb, 1, 'pending');
INSERT INTO vehicles (make, model, year, trim_level, vehicle_type, gcc_spec, chinese_spec, range_km, battery_kwh, price, manufacturer_direct_price, grey_market_price, grey_market_source, grey_market_url, description, specs, images, stock_count, status)
VALUES ('BYD', 'E2', 2025, 'Luxury', 'EV', true, false, 405, 43.2, 58400, 58400, NULL, NULL, NULL, 'BYD E2 - affordable electric hatchback with 405km range.', ''{"dimensions": {"length_mm": 4240, "width_mm": 1760, "height_mm": 1530, "wheelbase_mm": 2610}, "range_km": 405, "battery_kwh": 43.2, "acceleration_0_100": 9.3, "top_speed_kmh": 130, "power_kw": 70, "power_hp": 95, "drivetrain": "FWD", "body_style": "Hatchback"}''::jsonb, ''[]''::jsonb, 1, 'pending');
INSERT INTO vehicles (make, model, year, trim_level, vehicle_type, gcc_spec, chinese_spec, range_km, battery_kwh, price, manufacturer_direct_price, grey_market_price, grey_market_source, grey_market_url, description, specs, images, stock_count, status)
VALUES ('BYD', 'YUAN PLUS', 2025, 'Standard', 'EV', true, false, 510, 60.48, 120450, 120450, NULL, NULL, NULL, 'BYD YUAN PLUS - electric SUV with 510km range.', ''{"dimensions": {"length_mm": 4455, "width_mm": 1875, "height_mm": 1615, "wheelbase_mm": 2720}, "range_km": 510, "battery_kwh": 60.48, "acceleration_0_100": 7.5, "top_speed_kmh": 160, "power_kw": 150, "power_hp": 204, "drivetrain": "FWD", "body_style": "SUV"}''::jsonb, ''[]''::jsonb, 1, 'pending');
INSERT INTO vehicles (make, model, year, trim_level, vehicle_type, gcc_spec, chinese_spec, range_km, battery_kwh, price, manufacturer_direct_price, grey_market_price, grey_market_source, grey_market_url, description, specs, images, stock_count, status)
VALUES ('BYD', 'SONG L', 2025, 'Standard', 'EV', true, false, 550, 71.8, 67615, 67615, NULL, NULL, NULL, 'BYD SONG L - electric SUV coupe with 550km range.', ''{"dimensions": {"length_mm": 4840, "width_mm": 1950, "height_mm": 1560, "wheelbase_mm": 2930}, "range_km": 550, "battery_kwh": 71.8, "acceleration_0_100": 7.5, "top_speed_kmh": 170, "power_kw": 150, "power_hp": 204, "drivetrain": "FWD", "body_style": "SUV Coupe"}''::jsonb, ''[]''::jsonb, 1, 'pending');
INSERT INTO vehicles (make, model, year, trim_level, vehicle_type, gcc_spec, chinese_spec, range_km, battery_kwh, price, manufacturer_direct_price, grey_market_price, grey_market_source, grey_market_url, description, specs, images, stock_count, status)
VALUES ('BYD', 'SONG L', 2025, 'Performance', 'EV', true, false, 662, 87.04, 85000, 85000, NULL, NULL, NULL, 'BYD SONG L Performance with 4.5s acceleration and 662km range.', ''{"range_km": 662, "battery_kwh": 87.04, "acceleration_0_100": 4.5, "top_speed_kmh": 200, "power_kw": 230, "power_hp": 313, "drivetrain": "AWD", "body_style": "SUV Coupe"}''::jsonb, ''[]''::jsonb, 1, 'pending');
INSERT INTO vehicles (make, model, year, trim_level, vehicle_type, gcc_spec, chinese_spec, range_km, battery_kwh, price, manufacturer_direct_price, grey_market_price, grey_market_source, grey_market_url, description, specs, images, stock_count, status)
VALUES ('BYD', 'LEOPARD 5', 2025, 'Ultra 5', 'Hybrid', false, true, NULL, NULL, 165000, NULL, 165000, 'QatarSale', 'https://qatarsale.com/en/products/cars_for_sale/byd', 'BYD Leopard 5 (Fang Cheng Bao) - Chinese-spec grey market import via QatarSale. Petrol hybrid SUV.', ''{"drivetrain": "4WD", "body_style": "SUV", "seats": 5}''::jsonb, ''[]''::jsonb, 1, 'pending');
INSERT INTO vehicles (make, model, year, trim_level, vehicle_type, gcc_spec, chinese_spec, range_km, battery_kwh, price, manufacturer_direct_price, grey_market_price, grey_market_source, grey_market_url, description, specs, images, stock_count, status)
VALUES ('BYD', 'LEOPARD 7', 2025, 'Titanium 7', 'Hybrid', false, true, NULL, NULL, 143000, NULL, 143000, 'QatarSale', 'https://qatarsale.com/en/products/cars_for_sale/byd', 'BYD Leopard 7 - Chinese-spec grey market import via QatarSale. Petrol hybrid SUV.', ''{"drivetrain": "4WD", "body_style": "SUV"}''::jsonb, ''[]''::jsonb, 1, 'pending');
