INSERT INTO vehicles (make, model, year, trim_level, vehicle_type, gcc_spec, chinese_spec, range_km, battery_kwh, price, manufacturer_direct_price, grey_market_price, grey_market_source, grey_market_url, description, specs, images, stock_count, status)
VALUES ('BYD', 'LEOPARD 8', 2025, 'Flagship', 'Hybrid', false, true, NULL, NULL, 280000, NULL, 280000, 'QatarSale', 'https://qatarsale.com/en/products/cars_for_sale/byd', 'BYD Leopard 8 Flagship - Chinese-spec grey market import. Premium SUV with 6 seaters, 21 inch rims.', ''{"drivetrain": "4WD", "body_style": "SUV"}''::jsonb, ''[]''::jsonb, 1, 'pending');
INSERT INTO vehicles (make, model, year, trim_level, vehicle_type, gcc_spec, chinese_spec, range_km, battery_kwh, price, manufacturer_direct_price, grey_market_price, grey_market_source, grey_market_url, description, specs, images, stock_count, status)
VALUES ('BYD', 'DENZA B5', 2026, 'Flagship', 'Hybrid', false, true, 100, 31.8, 185000, 195000, 185000, 'QatarSale', NULL, 'BYD Denza B5 - plug-in hybrid off-road SUV with 1000km range, 790mm wading depth.', ''{"dimensions": {"length_mm": 5090, "width_mm": 1990, "height_mm": 1940, "wheelbase_mm": 2850}, "powertrain": {"power_kw": 400, "power_hp": 570, "torque_nm": 760}, "range_km": 100, "battery_kwh": 31.8, "drivetrain": "AWD", "body_style": "SUV"}''::jsonb, ''[]''::jsonb, 1, 'pending');
INSERT INTO vehicles (make, model, year, trim_level, vehicle_type, gcc_spec, chinese_spec, range_km, battery_kwh, price, manufacturer_direct_price, grey_market_price, grey_market_source, grey_market_url, description, specs, images, stock_count, status)
VALUES ('BYD', 'DENZA B8', 2026, 'Luxury', 'Hybrid', false, true, 100, 36.8, 243000, 242046, 243000, 'QatarSale', NULL, 'BYD Denza B8 - luxury plug-in hybrid SUV with 905km range, 890mm wading depth.', ''{"dimensions": {"length_mm": 5140, "width_mm": 1995, "height_mm": 1805, "wheelbase_mm": 3050}, "powertrain": {"power_kw": 450, "power_hp": 738, "torque_nm": 760}, "range_km": 100, "battery_kwh": 36.8, "drivetrain": "AWD", "body_style": "SUV"}''::jsonb, ''[]''::jsonb, 1, 'pending');
INSERT INTO vehicles (make, model, year, trim_level, vehicle_type, gcc_spec, chinese_spec, range_km, battery_kwh, price, manufacturer_direct_price, grey_market_price, grey_market_source, grey_market_url, description, specs, images, stock_count, status)
VALUES ('BYD', 'DENZA N9', 2025, 'Flagship', 'Hybrid', false, true, NULL, NULL, 229999, NULL, 229999, 'QatarSale', 'https://qatarsale.com/en/products/cars_for_sale/byd', 'BYD Denza N9 Flagship - Chinese-spec grey market import via QatarSale.', ''{"drivetrain": "AWD", "body_style": "SUV"}''::jsonb, ''[]''::jsonb, 1, 'pending');
INSERT INTO vehicles (make, model, year, trim_level, vehicle_type, gcc_spec, chinese_spec, range_km, battery_kwh, price, manufacturer_direct_price, grey_market_price, grey_market_source, grey_market_url, description, specs, images, stock_count, status)
VALUES ('GAC', 'AION Y Plus', 2024, 'Plus', 'EV', true, false, 430, 61.7, 89000, NULL, NULL, NULL, NULL, 'The GAC AION Y Plus is a fully electric suv offering 430 km of range
and 204 horsepower. It features modern electric vehicle technology with advanced battery systems,
comfortable interior with premium features, and comprehensive safety systems.', ''{"dimensions": {"length_mm": 4535, "width_mm": 1870, "height_mm": 1650, "wheelbase_mm": 2750, "ground_clearance_mm": 165}, "performance": {"acceleration_0_100kmh_s": 8.5, "top_speed_kmh": 150, "range_nedc_km": 430}, "powertrain": {"motor_type": "Permanent magnet synchronous motor", "peak_power_kw": 150, "peak_power_hp": 204, "max_torque_nm": 225, "drivetrain": "Front-wheel drive"}, "battery": {"type": "Lithium-ion NCM", "capacity_kwh": 61.7, "technology": "Nickel Cobalt Manganese"}, "charging": {"dc_charging_kw": 80, "ac_charging_kw": 7.2, "ac_charging_port": "Type 2", "dc_charging_port": "GB/T (China) / CCS (GCC)"}, "features": ["Hyper.dashboard - 14.6-inch touchscreen", "ADIGO intelligent driving system", "Panoramic sunroof", "Electric tailgate", "Hidden door handles", "LED matrix headlights", "Ambient lighting", "Wireless phone charging", "Voice control", "OTA updates", "ADAS (Advanced Driver Assistance Systems)", "360-degree camera", "Auto parking", "Adaptive cruise control", "Lane keep assist", "Blind spot monitoring", "Automatic emergency braking"], "safety": ["6 airbags", "Electronic Stability Program (ESP)", "Traction Control System (TCS)", "Hill Start Assist (HSA)", "Tyre Pressure Monitoring System (TPMS)", "ISOFIX child seat anchors", "Rear parking sensors", "Front and rear parking sensors"], "range_km": 430, "battery_kwh": 61.7, "acceleration_0_100": 8.5, "top_speed_kmh": 150, "power_kw": 150, "power_hp": 204, "drivetrain": "FWD", "body_style": "SUV", "seats": 5}''::jsonb, ''[{"type": "exterior_front", "url": "https://www.gacmotor.com/uploads/21012021074638456.jpg"}, {"type": "exterior_side", "url": "https://www.gacmotor.com/uploads/21012021074641389.jpg"}, {"type": "interior", "url": "https://www.gacmotor.com/uploads/21012021074643256.jpg"}, {"type": "exterior_rear", "url": "https://www.gacmotor.com/uploads/21012021074645123.jpg"}]''::jsonb, 1, 'pending');
INSERT INTO vehicles (make, model, year, trim_level, vehicle_type, gcc_spec, chinese_spec, range_km, battery_kwh, price, manufacturer_direct_price, grey_market_price, grey_market_source, grey_market_url, description, specs, images, stock_count, status)
VALUES ('GAC', 'AION S Plus', 2024, 'Plus', 'EV', true, false, 500, 58.8, 95000, NULL, NULL, NULL, NULL, 'The GAC AION S Plus is a fully electric sedan offering 500 km of range
and 204 horsepower. It features modern electric vehicle technology with advanced battery systems,
comfortable interior with premium features, and comprehensive safety systems.', ''{"dimensions": {"length_mm": 4800, "width_mm": 1880, "height_mm": 1515, "wheelbase_mm": 2750, "ground_clearance_mm": 130}, "performance": {"acceleration_0_100kmh_s": 7.5, "top_speed_kmh": 165, "range_nedc_km": 500}, "powertrain": {"motor_type": "Permanent magnet synchronous motor", "peak_power_kw": 150, "peak_power_hp": 204, "max_torque_nm": 235, "drivetrain": "Front-wheel drive"}, "battery": {"type": "Lithium-ion NCM", "capacity_kwh": 58.8, "technology": "Nickel Cobalt Manganese"}, "charging": {"dc_charging_kw": 100, "ac_charging_kw": 7.2, "dc_charging_time_30_to_80_min": 30}, "features": ["14.6-inch rotating touchscreen", "ADIGO 3.0 intelligent system", "LED headlights and taillights", "Panoramic sunroof", "Hidden door handles", "Ventilated front seats", "Heated front seats", "Electric driver seat adjustment", "Dual-zone climate control", "PM2.5 air filtration", "Wireless phone charger", "NFC card key", "Voice control", "OTA updates"], "safety": ["6 airbags", "C-NCAP 5-star rating", "ADAS with lane keep assist", "Adaptive cruise control", "Automatic emergency braking", "Blind spot detection", "Rear cross traffic alert", "360-degree camera", "Traffic sign recognition"], "range_km": 500, "battery_kwh": 58.8, "acceleration_0_100": 7.5, "top_speed_kmh": 165, "power_kw": 150, "power_hp": 204, "drivetrain": "FWD", "body_style": "Sedan", "seats": 5}''::jsonb, ''[{"type": "exterior_front", "url": "https://www.gacmotor.com/uploads/21012021074700123.jpg"}, {"type": "exterior_side", "url": "https://www.gacmotor.com/uploads/21012021074702456.jpg"}, {"type": "interior", "url": "https://www.gacmotor.com/uploads/21012021074704789.jpg"}]''::jsonb, 1, 'pending');
INSERT INTO vehicles (make, model, year, trim_level, vehicle_type, gcc_spec, chinese_spec, range_km, battery_kwh, price, manufacturer_direct_price, grey_market_price, grey_market_source, grey_market_url, description, specs, images, stock_count, status)
VALUES ('GAC', 'AION LX Plus', 2024, 'Plus', 'EV', true, false, 600, 93.3, 145000, NULL, NULL, NULL, NULL, 'The GAC AION LX Plus is a fully electric suv offering 600 km of range
and 408 horsepower. It features modern electric vehicle technology with advanced battery systems,
comfortable interior with premium features, and comprehensive safety systems.', ''{"dimensions": {"length_mm": 4835, "width_mm": 1935, "height_mm": 1685, "wheelbase_mm": 2920, "ground_clearance_mm": 170}, "performance": {"acceleration_0_100kmh_s": 4.5, "top_speed_kmh": 180, "range_nedc_km": 600}, "powertrain": {"motor_type": "Dual motor AWD", "peak_power_kw": 300, "peak_power_hp": 408, "max_torque_nm": 450, "drivetrain": "All-wheel drive"}, "battery": {"type": "Lithium-ion NCM", "capacity_kwh": 93.3, "technology": "Nickel Cobalt Manganese", "cell_technology": "811 NCM cells"}, "charging": {"dc_charging_kw": 150, "ac_charging_kw": 11, "dc_charging_time_30_to_80_min": 18}, "features": ["15.6-inch touchscreen", "ADIGO 3.0 intelligent system", "Nappa leather seats", "Ventilated and massaging front seats", "Heated rear seats", "21-speaker audio system", "Panoramic sunroof", "HUD (Head-Up Display)", "Wireless phone charger", "Ambient lighting - 64 colors", "Triple-zone climate control", "PM2.5 air filtration", "Fragrance system", "OTA updates", "V2L (Vehicle-to-Load)"], "safety": ["6 airbags", "C-NCAP 5-star rating", "Level 2 ADAS", "Adaptive cruise control", "Lane centering", "Automatic emergency braking", "Blind spot monitoring", "Rear cross traffic alert", "360-degree camera", "Traffic sign recognition", "Driver monitoring system"], "range_km": 600, "battery_kwh": 93.3, "acceleration_0_100": 4.5, "top_speed_kmh": 180, "power_kw": 300, "power_hp": 408, "drivetrain": "AWD", "body_style": "SUV", "seats": 5}''::jsonb, ''[{"type": "exterior_front", "url": "https://www.gacmotor.com/uploads/21012021074720012.jpg"}, {"type": "exterior_side", "url": "https://www.gacmotor.com/uploads/21012021074722345.jpg"}, {"type": "interior", "url": "https://www.gacmotor.com/uploads/21012021074724678.jpg"}]''::jsonb, 1, 'pending');
INSERT INTO vehicles (make, model, year, trim_level, vehicle_type, gcc_spec, chinese_spec, range_km, battery_kwh, price, manufacturer_direct_price, grey_market_price, grey_market_source, grey_market_url, description, specs, images, stock_count, status)
VALUES ('GAC', 'AION V', 2024, 'Plus', 'EV', true, false, 400, 60.0, 92000, NULL, NULL, NULL, NULL, 'The GAC AION V is a fully electric suv offering 400 km of range
and 224 horsepower. It features modern electric vehicle technology with advanced battery systems,
comfortable interior with premium features, and comprehensive safety systems.', ''{"dimensions": {"length_mm": 4586, "width_mm": 1865, "height_mm": 1660, "wheelbase_mm": 2830, "ground_clearance_mm": 175}, "performance": {"acceleration_0_100kmh_s": 8.0, "top_speed_kmh": 160, "range_nedc_km": 400}, "powertrain": {"motor_type": "Permanent magnet synchronous motor", "peak_power_kw": 165, "peak_power_hp": 224, "max_torque_nm": 280, "drivetrain": "Front-wheel drive"}, "battery": {"type": "Lithium-ion NCM", "capacity_kwh": 60.0, "technology": "Nickel Cobalt Manganese"}, "charging": {"dc_charging_kw": 80, "ac_charging_kw": 7.2}, "features": ["12.3-inch touchscreen", "ADIGO intelligent system", "Panoramic sunroof", "Electric tailgate", "LED headlights", "Alloy wheels", "Automatic climate control", "Rear parking sensors", "360-degree camera"], "safety": ["6 airbags", "Electronic Stability Program", "Traction Control", "Hill Start Assist", "Tyre Pressure Monitoring", "ISOFIX anchors"], "range_km": 400, "battery_kwh": 60.0, "acceleration_0_100": 8.0, "top_speed_kmh": 160, "power_kw": 165, "power_hp": 224, "drivetrain": "FWD", "body_style": "SUV", "seats": 5}''::jsonb, ''[{"type": "exterior_front", "url": "https://www.gacmotor.com/uploads/21012021074740012.jpg"}, {"type": "exterior_side", "url": "https://www.gacmotor.com/uploads/21012021074742345.jpg"}]''::jsonb, 1, 'pending');
INSERT INTO vehicles (make, model, year, trim_level, vehicle_type, gcc_spec, chinese_spec, range_km, battery_kwh, price, manufacturer_direct_price, grey_market_price, grey_market_source, grey_market_url, description, specs, images, stock_count, status)
VALUES ('GAC', 'AION ES', 2024, 'Standard', 'EV', false, true, 350, 52.1, NULL, NULL, NULL, NULL, NULL, 'The GAC AION ES is a fully electric sedan offering 350 km of range
and 136 horsepower. It features modern electric vehicle technology with advanced battery systems,
comfortable interior with premium features, and comprehensive safety systems.', ''{"dimensions": {"length_mm": 4680, "width_mm": 1800, "height_mm": 1510, "wheelbase_mm": 2700}, "performance": {"acceleration_0_100kmh_s": 9.5, "top_speed_kmh": 140, "range_nedc_km": 350}, "powertrain": {"motor_type": "Permanent magnet synchronous motor", "peak_power_kw": 100, "peak_power_hp": 136, "max_torque_nm": 180, "drivetrain": "Front-wheel drive"}, "battery": {"type": "Lithium-ion NCM", "capacity_kwh": 52.1}, "charging": {"dc_charging_kw": 60, "ac_charging_kw": 6.6}, "range_km": 350, "battery_kwh": 52.1, "acceleration_0_100": 9.5, "top_speed_kmh": 140, "power_kw": 100, "power_hp": 136, "drivetrain": "FWD", "body_style": "Sedan", "seats": 5}''::jsonb, ''[]''::jsonb, 1, 'pending');
INSERT INTO vehicles (make, model, year, trim_level, vehicle_type, gcc_spec, chinese_spec, range_km, battery_kwh, price, manufacturer_direct_price, grey_market_price, grey_market_source, grey_market_url, description, specs, images, stock_count, status)
VALUES ('Chery', 'eQ7', 2025, 'Standard', 'EV', false, true, 512, 67.12, 95000, NULL, 95000, 'Grey Market / China Import', NULL, 'Chery eQ7 - Pure electric SUV with 512km range, 67.12kWh LFP battery. Grey market import from China.', ''{"dimensions": {"length_mm": 4675, "width_mm": 1865, "height_mm": 1680, "wheelbase_mm": 2715}, "battery": {"type": "Lithium Iron Phosphate (LFP)", "capacity_kwh": 67.12, "charging_time_dc_min": 45}, "features": ["LFP Battery Pack", "Single Motor FWD", "512km CLTC Range"], "range_km": 512, "battery_kwh": 67.12, "acceleration_0_100": 8.5, "top_speed_kmh": 170, "power_kw": 155, "power_hp": 208, "drivetrain": "FWD", "body_style": "SUV", "seats": 5}''::jsonb, ''[{"url": "https://www.autocango.com/carspecs-detail/Chery-EV-eQ7-RD3AKB", "type": "exterior", "is_primary": true}]''::jsonb, 1, 'pending');
