INSERT INTO vehicles (make, model, year, trim_level, vehicle_type, gcc_spec, chinese_spec, range_km, battery_kwh, price, manufacturer_direct_price, grey_market_price, grey_market_source, grey_market_url, description, specs, images, stock_count, status)
VALUES ('BYD', 'SEAL', 2025, 'Long Range FWD', 'EV', true, false, 570, 82.5, 142700, 142700, NULL, NULL, NULL, 'BYD SEAL is an all-electric sedan with ocean-inspired aesthetics, featuring CTB technology and exceptional performance.', ''{"dimensions": {"length_mm": 4800, "width_mm": 1875, "height_mm": 1460, "wheelbase_mm": 2920}, "battery": {"type": "BYD Blade Battery (LFP)", "technology": "Lithium Iron Phosphate"}, "charging": {"dc_charging_kw": 150, "ac_charging_kw": 11, "charging_time_30_80_min": 26}, "features": ["CTB Technology", "iTAC", "e-Platform 3.0", "Heat pump", "8-in-1 electric powertrain"], "range_km": 570, "battery_kwh": 82.5, "acceleration_0_100": 5.9, "top_speed_kmh": 180, "power_kw": 230, "power_hp": 313, "drivetrain": "RWD", "body_style": "Sedan", "seats": 5}''::jsonb, ''[{"url": "https://www.bydqatar.com.qa/wp-content/uploads/2024/09/section02-scaled.jpg", "type": "exterior", "is_primary": true}]''::jsonb, 1, 'pending');
INSERT INTO vehicles (make, model, year, trim_level, vehicle_type, gcc_spec, chinese_spec, range_km, battery_kwh, price, manufacturer_direct_price, grey_market_price, grey_market_source, grey_market_url, description, specs, images, stock_count, status)
VALUES ('BYD', 'SEAL', 2025, 'Flagship AWD', 'EV', true, false, 460, 82.5, 171698, 171698, NULL, NULL, NULL, 'BYD SEAL Flagship AWD with dual motors, 3.8s 0-100 km/h acceleration.', ''{"dimensions": {"length_mm": 4800, "width_mm": 1875, "height_mm": 1460, "wheelbase_mm": 2920}, "battery": {"type": "BYD Blade Battery (LFP)", "technology": "Lithium Iron Phosphate"}, "charging": {"dc_charging_kw": 150, "ac_charging_kw": 11, "charging_time_30_80_min": 26}, "range_km": 460, "battery_kwh": 82.5, "acceleration_0_100": 3.8, "top_speed_kmh": 180, "power_kw": 390, "power_hp": 530, "drivetrain": "AWD", "body_style": "Sedan", "seats": 5}''::jsonb, ''[{"url": "https://www.bydqatar.com.qa/wp-content/uploads/2024/09/section02-scaled.jpg", "type": "exterior", "is_primary": true}]''::jsonb, 1, 'pending');
INSERT INTO vehicles (make, model, year, trim_level, vehicle_type, gcc_spec, chinese_spec, range_km, battery_kwh, price, manufacturer_direct_price, grey_market_price, grey_market_source, grey_market_url, description, specs, images, stock_count, status)
VALUES ('BYD', 'ATTO 3', 2025, 'Standard', 'EV', true, false, 420, 60.48, 108987, 108987, NULL, NULL, NULL, 'BYD ATTO 3 is a compact electric SUV with 420km range, featuring the signature rotating display.', ''{"dimensions": {"length_mm": 4455, "width_mm": 1875, "height_mm": 1615, "wheelbase_mm": 2720}, "battery": {"type": "BYD Blade Battery (LFP)", "capacity_kwh": 60.48}, "charging": {"dc_charging_kw": 88, "ac_charging_kw": 7.4}, "features": ["12.8-inch rotating screen", "DiPilot", "VTOL mobile power supply"], "range_km": 420, "battery_kwh": 60.48, "acceleration_0_100": 7.3, "top_speed_kmh": 160, "power_kw": 150, "power_hp": 204, "drivetrain": "FWD", "body_style": "SUV", "seats": 5}''::jsonb, ''[]''::jsonb, 1, 'pending');
INSERT INTO vehicles (make, model, year, trim_level, vehicle_type, gcc_spec, chinese_spec, range_km, battery_kwh, price, manufacturer_direct_price, grey_market_price, grey_market_source, grey_market_url, description, specs, images, stock_count, status)
VALUES ('BYD', 'ATTO 3', 2025, 'Plus', 'EV', true, false, 420, 60.48, 116062, 116062, NULL, NULL, NULL, 'BYD ATTO 3 Plus trim with enhanced features.', ''{"range_km": 420, "battery_kwh": 60.48, "acceleration_0_100": 7.3, "top_speed_kmh": 160, "power_kw": 150, "power_hp": 204, "drivetrain": "FWD", "body_style": "SUV"}''::jsonb, ''[]''::jsonb, 1, 'pending');
INSERT INTO vehicles (make, model, year, trim_level, vehicle_type, gcc_spec, chinese_spec, range_km, battery_kwh, price, manufacturer_direct_price, grey_market_price, grey_market_source, grey_market_url, description, specs, images, stock_count, status)
VALUES ('BYD', 'HAN EV', 2025, 'AWD', 'EV', true, false, 521, 85.4, 197348, 197348, NULL, NULL, NULL, 'BYD HAN EV luxury sedan with dual motors, 521km range.', ''{"dimensions": {"length_mm": 4995, "width_mm": 1910, "height_mm": 1495, "wheelbase_mm": 2920}, "battery": {"type": "BYD Blade Battery (LFP)", "capacity_kwh": 85.4}, "range_km": 521, "battery_kwh": 85.4, "acceleration_0_100": 3.9, "top_speed_kmh": 180, "power_kw": 380, "power_hp": 530, "drivetrain": "AWD", "body_style": "Sedan", "seats": 5}''::jsonb, ''[{"url": "https://www.bydqatar.com.qa/wp-content/uploads/2024/10/21-scaled.jpg", "type": "exterior_front", "is_primary": true}]''::jsonb, 1, 'pending');
INSERT INTO vehicles (make, model, year, trim_level, vehicle_type, gcc_spec, chinese_spec, range_km, battery_kwh, price, manufacturer_direct_price, grey_market_price, grey_market_source, grey_market_url, description, specs, images, stock_count, status)
VALUES ('BYD', 'DOLPHIN', 2025, 'Standard', 'EV', true, false, 340, 44.9, 52925, 52925, NULL, NULL, NULL, 'BYD DOLPHIN - affordable electric hatchback with 340km range.', ''{"dimensions": {"length_mm": 4290, "width_mm": 1770, "height_mm": 1570, "wheelbase_mm": 2700}, "range_km": 340, "battery_kwh": 44.9, "acceleration_0_100": 12.3, "top_speed_kmh": 150, "power_kw": 95, "power_hp": 130, "drivetrain": "FWD", "body_style": "Hatchback", "seats": 5}''::jsonb, ''[]''::jsonb, 1, 'pending');
INSERT INTO vehicles (make, model, year, trim_level, vehicle_type, gcc_spec, chinese_spec, range_km, battery_kwh, price, manufacturer_direct_price, grey_market_price, grey_market_source, grey_market_url, description, specs, images, stock_count, status)
VALUES ('BYD', 'DOLPHIN', 2025, 'Premium', 'EV', true, false, 427, 60.4, 67708, 67708, NULL, NULL, NULL, 'BYD DOLPHIN Premium with 60.4kWh battery and 427km range.', ''{"range_km": 427, "battery_kwh": 60.4, "acceleration_0_100": 7.0, "top_speed_kmh": 160, "power_kw": 150, "power_hp": 204, "drivetrain": "FWD", "body_style": "Hatchback"}''::jsonb, ''[]''::jsonb, 1, 'pending');
INSERT INTO vehicles (make, model, year, trim_level, vehicle_type, gcc_spec, chinese_spec, range_km, battery_kwh, price, manufacturer_direct_price, grey_market_price, grey_market_source, grey_market_url, description, specs, images, stock_count, status)
VALUES ('BYD', 'SEALION 7', 2025, 'Excellence AWD', 'EV', true, false, 482, 80.64, 228490, 228490, NULL, NULL, NULL, 'BYD SEALION 7 - premium electric SUV with Nappa leather, 523HP, 482km range.', ''{"dimensions": {"length_mm": 4830, "width_mm": 1920, "height_mm": 1720, "wheelbase_mm": 2830}, "range_km": 482, "battery_kwh": 80.64, "acceleration_0_100": 4.5, "top_speed_kmh": 180, "power_kw": 390, "power_hp": 523, "drivetrain": "AWD", "body_style": "SUV", "seats": 5}''::jsonb, ''[{"url": "https://www.bydqatar.com.qa/wp-content/uploads/2024/12/byd-sealion-7-exterior-01-l-scaled.jpg", "type": "exterior_front", "is_primary": true}, {"url": "https://www.bydqatar.com.qa/wp-content/uploads/2024/12/byd-sealion-7-exterior-02-l-scaled.jpg", "type": "exterior_side", "is_primary": false}, {"url": "https://www.bydqatar.com.qa/wp-content/uploads/2024/12/byd-sealion-7-interior-01-l-scaled.jpg", "type": "interior", "is_primary": false}]''::jsonb, 1, 'pending');
INSERT INTO vehicles (make, model, year, trim_level, vehicle_type, gcc_spec, chinese_spec, range_km, battery_kwh, price, manufacturer_direct_price, grey_market_price, grey_market_source, grey_market_url, description, specs, images, stock_count, status)
VALUES ('BYD', 'SHARK 6', 2025, 'Premium', 'Hybrid', true, false, 520, 29.58, 157311, 157311, NULL, NULL, NULL, 'BYD SHARK 6 - plug-in hybrid pickup with DMO off-road system, 2500kg towing.', ''{"dimensions": {"length_mm": 5260, "width_mm": 1940, "height_mm": 1920, "wheelbase_mm": 3120}, "technology": ["DMO Hybrid System", "V2L", "2500kg towing capacity"], "range_km": 520, "battery_kwh": 29.58, "acceleration_0_100": 5.7, "top_speed_kmh": 160, "power_kw": 321, "power_hp": 430, "drivetrain": "AWD", "body_style": "Pickup Truck"}''::jsonb, ''[]''::jsonb, 1, 'pending');
INSERT INTO vehicles (make, model, year, trim_level, vehicle_type, gcc_spec, chinese_spec, range_km, battery_kwh, price, manufacturer_direct_price, grey_market_price, grey_market_source, grey_market_url, description, specs, images, stock_count, status)
VALUES ('BYD', 'SEAL 7 DM-i', 2025, 'Standard', 'Hybrid', true, false, 850, 17.6, 104667, 104667, NULL, NULL, NULL, 'BYD SEAL 7 DM-i - plug-in hybrid sedan with 850km combined range, DM-i Gen 4.0.', ''{"dimensions": {"length_mm": 4830, "width_mm": 1890, "height_mm": 1495, "wheelbase_mm": 2900}, "range_km": 850, "battery_kwh": 17.6, "acceleration_0_100": 6.5, "top_speed_kmh": 180, "power_kw": 200, "power_hp": 270, "drivetrain": "FWD", "body_style": "Sedan"}''::jsonb, ''[{"url": "https://www.bydqatar.com.qa/wp-content/uploads/2025/04/kv4pc-scaled.png", "type": "exterior", "is_primary": true}]''::jsonb, 1, 'pending');
