INSERT INTO vehicles (make, model, year, trim_level, vehicle_type, gcc_spec, chinese_spec, range_km, battery_kwh, price, manufacturer_direct_price, grey_market_price, grey_market_source, grey_market_url, description, specs, images, stock_count, status)
VALUES ('Geely', 'Geometry C', 2025, 'GS 53 kWh', 'EV', false, true, 400, 53, 130680, NULL, 132000, 'UAE import via QatarSale', NULL, 'Geely Geometry C GS 53 kWh - Electric SUV crossover available through UAE imports. 400km range, 201HP.', ''{"dimensions": {"length_mm": 4432, "width_mm": 1833, "height_mm": 1560, "wheelbase_mm": 2700}, "battery": {"type": "Lithium-ion", "capacity_kwh": 53, "range_km": 400}, "charging": {"dc_charging_kw": 100, "ac_charging_kw": 6.6}, "features": ["201 HP electric motor", "400km range", "Futuristic design", "UAE official specs"], "range_km": 400, "battery_kwh": 53, "acceleration_0_100": 7.7, "top_speed_kmh": 150, "power_kw": 150, "power_hp": 201, "drivetrain": "FWD", "body_style": "SUV Crossover", "seats": 5}''::jsonb, ''[{"url": "https://www.geely.ae/car/geometry-c", "type": "exterior", "is_primary": true}]''::jsonb, 1, 'pending');
INSERT INTO vehicles (make, model, year, trim_level, vehicle_type, gcc_spec, chinese_spec, range_km, battery_kwh, price, manufacturer_direct_price, grey_market_price, grey_market_source, grey_market_url, description, specs, images, stock_count, status)
VALUES ('Geely', 'Geometry C', 2025, 'GF 70 kWh Long Range', 'EV', false, true, 485, 70, 155430, NULL, 155430, 'UAE import via QatarSale', NULL, 'Geely Geometry C GF 70 kWh Long Range - Extended range version with 485km WLTP range.', ''{"battery": {"capacity_kwh": 70, "range_km": 485}, "range_km": 485, "battery_kwh": 70, "acceleration_0_100": 7.7, "top_speed_kmh": 150, "power_kw": 150, "power_hp": 201, "drivetrain": "FWD", "body_style": "SUV Crossover", "seats": 5}''::jsonb, ''[]''::jsonb, 1, 'pending');
INSERT INTO vehicles (make, model, year, trim_level, vehicle_type, gcc_spec, chinese_spec, range_km, battery_kwh, price, manufacturer_direct_price, grey_market_price, grey_market_source, grey_market_url, description, specs, images, stock_count, status)
VALUES ('Geely', 'Monjaro', 2025, 'Standard', 'ICE', true, false, NULL, NULL, 118000, 118000, NULL, NULL, NULL, 'Geely Monjaro - Flagship SUV with 2.0L turbo engine, AWD, and premium features. Officially available in Qatar.', ''{"dimensions": {"length_mm": 4770, "width_mm": 1895, "height_mm": 1689, "wheelbase_mm": 2845}, "engine": {"displacement_l": 2.0, "power_kw": 175, "power_hp": 238, "torque_nm": 350, "fuel_economy_l_100km": 8.8}, "features": ["2.0L turbocharged engine", "238 HP", "AWD system", "Premium interior", "360-degree camera"], "drivetrain": "AWD", "body_style": "SUV", "seats": 5}''::jsonb, ''[{"url": "https://geely.com.qa/the_new_monjaro/", "type": "exterior", "is_primary": true}]''::jsonb, 1, 'pending');
INSERT INTO vehicles (make, model, year, trim_level, vehicle_type, gcc_spec, chinese_spec, range_km, battery_kwh, price, manufacturer_direct_price, grey_market_price, grey_market_source, grey_market_url, description, specs, images, stock_count, status)
VALUES ('Geely', 'Tugella', 2025, 'GF', 'ICE', true, false, NULL, NULL, 117087, 117087, NULL, NULL, NULL, 'Geely Tugella GF - Performance SUV coupe with sporty styling.', ''{"features": ["Performance SUV coupe", "AWD system", "Sporty design"], "drivetrain": "AWD", "body_style": "SUV Coupe", "seats": 5}''::jsonb, ''[]''::jsonb, 1, 'pending');
INSERT INTO vehicles (make, model, year, trim_level, vehicle_type, gcc_spec, chinese_spec, range_km, battery_kwh, price, manufacturer_direct_price, grey_market_price, grey_market_source, grey_market_url, description, specs, images, stock_count, status)
VALUES ('Geely', 'Tugella', 2025, 'GF+', 'ICE', true, false, NULL, NULL, 126454, 126454, NULL, NULL, NULL, 'Geely Tugella GF+ - Enhanced trim level.', ''{"drivetrain": "AWD", "body_style": "SUV Coupe"}''::jsonb, ''[]''::jsonb, 1, 'pending');
INSERT INTO vehicles (make, model, year, trim_level, vehicle_type, gcc_spec, chinese_spec, range_km, battery_kwh, price, manufacturer_direct_price, grey_market_price, grey_market_source, grey_market_url, description, specs, images, stock_count, status)
VALUES ('Geely', 'Tugella', 2025, 'GF+ BR', 'ICE', true, false, NULL, NULL, 129365, 129365, NULL, NULL, NULL, 'Geely Tugella GF+ BR - Premium trim with brown interior package.', ''{"drivetrain": "AWD", "body_style": "SUV Coupe"}''::jsonb, ''[]''::jsonb, 1, 'pending');
INSERT INTO vehicles (make, model, year, trim_level, vehicle_type, gcc_spec, chinese_spec, range_km, battery_kwh, price, manufacturer_direct_price, grey_market_price, grey_market_source, grey_market_url, description, specs, images, stock_count, status)
VALUES ('Geely', 'Emgrand', 2025, 'Standard', 'ICE', true, false, NULL, NULL, 49900, 49900, NULL, NULL, NULL, 'Geely Emgrand - Entry-level sedan, most affordable Geely in Qatar.', ''{"engine": {"power_kw": 90, "power_hp": 120, "torque_nm": 152, "fuel_economy_l_100km": 6.4}, "features": ["Affordable sedan", "120 HP", "6.4 L/100km fuel economy"], "drivetrain": "FWD", "body_style": "Sedan", "seats": 5}''::jsonb, ''[]''::jsonb, 1, 'pending');
INSERT INTO vehicles (make, model, year, trim_level, vehicle_type, gcc_spec, chinese_spec, range_km, battery_kwh, price, manufacturer_direct_price, grey_market_price, grey_market_source, grey_market_url, description, specs, images, stock_count, status)
VALUES ('Geely', 'Coolray', 2025, 'Comfort', 'ICE', true, false, NULL, NULL, 57990, 57990, NULL, NULL, NULL, 'Geely Coolray Comfort - Compact SUV with turbocharged engine.', ''{"features": ["Compact SUV", "Turbocharged engine", "Affordable pricing"], "drivetrain": "FWD", "body_style": "SUV"}''::jsonb, ''[]''::jsonb, 1, 'pending');
INSERT INTO vehicles (make, model, year, trim_level, vehicle_type, gcc_spec, chinese_spec, range_km, battery_kwh, price, manufacturer_direct_price, grey_market_price, grey_market_source, grey_market_url, description, specs, images, stock_count, status)
VALUES ('Geely', 'Starray', 2025, 'Standard', 'ICE', true, false, NULL, NULL, 84000, 84000, NULL, NULL, NULL, 'Geely Starray - Mid-size SUV.', ''{"drivetrain": "FWD", "body_style": "SUV"}''::jsonb, ''[]''::jsonb, 1, 'pending');
INSERT INTO vehicles (make, model, year, trim_level, vehicle_type, gcc_spec, chinese_spec, range_km, battery_kwh, price, manufacturer_direct_price, grey_market_price, grey_market_source, grey_market_url, description, specs, images, stock_count, status)
VALUES ('Geely', 'Galaxy L6', 2025, 'EM-i PHEV', 'Hybrid', false, true, 100, 18.4, 95000, NULL, NULL, 'China/UAE import', NULL, 'Geely Galaxy L6 EM-i - Advanced plug-in hybrid sedan with 1370km total range. Grey market import.', ''{"powertrain": {"engine": "1.5L turbo", "electric_motor": "DHT Pro hybrid system", "combined_power_hp": 180, "electric_range_km": 100, "combined_range_km": 1370}, "features": ["Fourth-generation DM-i hybrid technology", "100km electric range", "1370km total range", "Advanced connectivity"], "range_km": 100, "battery_kwh": 18.4, "drivetrain": "FWD", "body_style": "Sedan", "seats": 5}''::jsonb, ''[]''::jsonb, 1, 'pending');
