INSERT INTO vehicles (make, model, year, trim_level, vehicle_type, gcc_spec, chinese_spec, range_km, battery_kwh, price, manufacturer_direct_price, grey_market_price, grey_market_source, grey_market_url, description, specs, images, stock_count, status)
VALUES ('Omoda', 'C5', 2025, '1.5T Basic', 'ICE', true, false, NULL, NULL, 80000, 80000, 59000, 'QIC Car Market', NULL, 'Omoda C5 1.5T Basic - Entry-level crossover SUV with 1.5L turbo engine. Official GCC spec available.', ''{"dimensions": {"length_mm": 4400, "width_mm": 1830, "height_mm": 1588, "wheelbase_mm": 2630}, "engine": {"type": "1.5L Turbocharged", "power_hp": 147, "transmission": "CVT"}, "features": ["1.5L Turbo Engine", "CVT Transmission", "FWD"], "drivetrain": "FWD", "body_style": "SUV", "seats": 5}''::jsonb, ''[]''::jsonb, 1, 'pending');
INSERT INTO vehicles (make, model, year, trim_level, vehicle_type, gcc_spec, chinese_spec, range_km, battery_kwh, price, manufacturer_direct_price, grey_market_price, grey_market_source, grey_market_url, description, specs, images, stock_count, status)
VALUES ('Omoda', 'C5', 2025, '1.6T Sport', 'ICE', true, false, NULL, NULL, 87657, 87657, NULL, NULL, NULL, 'Omoda C5 1.6T Sport - Sport trim with more powerful 1.6L turbo engine.', ''{"engine": {"type": "1.6L Turbocharged", "power_hp": 197, "transmission": "7DCT"}, "drivetrain": "FWD", "body_style": "SUV", "seats": 5}''::jsonb, ''[]''::jsonb, 1, 'pending');
INSERT INTO vehicles (make, model, year, trim_level, vehicle_type, gcc_spec, chinese_spec, range_km, battery_kwh, price, manufacturer_direct_price, grey_market_price, grey_market_source, grey_market_url, description, specs, images, stock_count, status)
VALUES ('Omoda', 'C5', 2025, 'Flagship', 'ICE', true, false, NULL, NULL, 135000, 135000, NULL, NULL, NULL, 'Omoda C5 Flagship - Top trim with premium features and 1.6L turbo engine.', ''{"engine": {"type": "1.6L Turbocharged", "power_hp": 197}, "drivetrain": "FWD", "body_style": "SUV", "seats": 5}''::jsonb, ''[]''::jsonb, 1, 'pending');
INSERT INTO vehicles (make, model, year, trim_level, vehicle_type, gcc_spec, chinese_spec, range_km, battery_kwh, price, manufacturer_direct_price, grey_market_price, grey_market_source, grey_market_url, description, specs, images, stock_count, status)
VALUES ('Omoda', 'S5 GT', 2024, 'Luxury', 'ICE', true, false, NULL, NULL, 73999, 73999, 42000, 'QatarSale', NULL, 'Omoda S5 GT Luxury - Sporty sedan with 1.6L turbo engine. Available via official and grey market channels.', ''{"dimensions": {"length_mm": 4780, "width_mm": 1843, "height_mm": 1469, "wheelbase_mm": 2790}, "engine": {"type": "1.6L Turbocharged", "power_hp": 150, "power_kw": 110, "torque_nm": 275, "transmission": "AMT"}, "features": ["1.6L Turbo Engine", "150 hp", "275 Nm Torque", "RWD"], "drivetrain": "RWD", "body_style": "Sedan", "seats": 5}''::jsonb, ''[]''::jsonb, 1, 'pending');
INSERT INTO vehicles (make, model, year, trim_level, vehicle_type, gcc_spec, chinese_spec, range_km, battery_kwh, price, manufacturer_direct_price, grey_market_price, grey_market_source, grey_market_url, description, specs, images, stock_count, status)
VALUES ('Omoda', 'S5 GT', 2024, 'Standard', 'ICE', true, false, NULL, NULL, 65000, 65000, 49500, 'QatarSale', NULL, 'Omoda S5 GT Standard - Entry-level sport sedan with 1.5L turbo engine.', ''{"engine": {"type": "1.5L Turbocharged", "power_hp": 147, "torque_nm": 210, "transmission": "CVT"}, "drivetrain": "RWD", "body_style": "Sedan", "seats": 5}''::jsonb, ''[]''::jsonb, 1, 'pending');
INSERT INTO vehicles (make, model, year, trim_level, vehicle_type, gcc_spec, chinese_spec, range_km, battery_kwh, price, manufacturer_direct_price, grey_market_price, grey_market_source, grey_market_url, description, specs, images, stock_count, status)
VALUES ('Omoda', '5', 2024, 'Luxury', 'ICE', false, true, NULL, NULL, 79900, NULL, 79900, 'QatarSale', NULL, 'Omoda 5 Luxury - Chinese-spec grey market import via QatarSale. Compact crossover SUV.', ''{"drivetrain": "FWD", "body_style": "SUV", "seats": 5}''::jsonb, ''[]''::jsonb, 1, 'pending');
INSERT INTO vehicles (make, model, year, trim_level, vehicle_type, gcc_spec, chinese_spec, range_km, battery_kwh, price, manufacturer_direct_price, grey_market_price, grey_market_source, grey_market_url, description, specs, images, stock_count, status)
VALUES ('Chery', 'TIGGO 8 PRO MAX', 2025, 'AWD', 'ICE', true, false, NULL, NULL, 109000, 109000, NULL, NULL, NULL, 'Chery Tiggo 8 Pro Max AWD - Flagship SUV with 2.0L turbo engine. Official GCC spec from Elite Motors.', ''{"engine": {"type": "2.0L Turbocharged", "power_hp": 251, "torque_nm": 390}, "features": ["Flagship SUV", "2.0L Turbo Engine", "AWD"], "drivetrain": "AWD", "body_style": "SUV", "seats": 5}''::jsonb, ''[{"url": "https://cheryqatar.com/sites/default/files/2024-10/T1D-2.0T-Exterior%20%283%29.jpg", "type": "exterior", "is_primary": true}]''::jsonb, 1, 'pending');
INSERT INTO vehicles (make, model, year, trim_level, vehicle_type, gcc_spec, chinese_spec, range_km, battery_kwh, price, manufacturer_direct_price, grey_market_price, grey_market_source, grey_market_url, description, specs, images, stock_count, status)
VALUES ('Chery', 'TIGGO 8 PRO', 2025, 'Standard', 'ICE', true, false, NULL, NULL, 89500, 89500, NULL, NULL, NULL, 'Chery Tiggo 8 Pro - Mid-size SUV with 1.6L turbo engine.', ''{"engine": {"type": "1.6L Turbocharged", "power_hp": 197}, "drivetrain": "FWD", "body_style": "SUV", "seats": 5}''::jsonb, ''[{"url": "https://cheryqatar.com/sites/default/files/2023-02/root1675322558875315.jpg", "type": "exterior", "is_primary": true}]''::jsonb, 1, 'pending');
INSERT INTO vehicles (make, model, year, trim_level, vehicle_type, gcc_spec, chinese_spec, range_km, battery_kwh, price, manufacturer_direct_price, grey_market_price, grey_market_source, grey_market_url, description, specs, images, stock_count, status)
VALUES ('Chery', 'TIGGO 7 PRO MAX', 2025, 'Standard', 'ICE', true, false, NULL, NULL, 69500, 69500, NULL, NULL, NULL, 'Chery Tiggo 7 Pro Max - Compact SUV with premium features.', ''{"engine": {"type": "1.6L Turbocharged", "power_hp": 197}, "drivetrain": "FWD", "body_style": "SUV", "seats": 5}''::jsonb, ''[{"url": "https://cheryqatar.com/sites/default/files/2023-05/WEBSITE%202_0.png", "type": "exterior", "is_primary": true}]''::jsonb, 1, 'pending');
INSERT INTO vehicles (make, model, year, trim_level, vehicle_type, gcc_spec, chinese_spec, range_km, battery_kwh, price, manufacturer_direct_price, grey_market_price, grey_market_source, grey_market_url, description, specs, images, stock_count, status)
VALUES ('Chery', 'TIGGO 7 PRO', 2025, 'Standard', 'ICE', true, false, NULL, NULL, 64500, 64500, NULL, NULL, NULL, 'Chery Tiggo 7 Pro - Compact SUV with 1.5L turbo engine.', ''{"engine": {"type": "1.5L Turbocharged", "power_hp": 156}, "drivetrain": "FWD", "body_style": "SUV", "seats": 5}''::jsonb, ''[{"url": "https://cheryqatar.com/sites/default/files/2023-02/tiggo%207%20pro.jpg", "type": "exterior", "is_primary": true}]''::jsonb, 1, 'pending');
