'use client'

import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import { Button } from '@/components/ui/button'
import { Badge } from '@/components/ui/badge'
import { DocumentIcon } from '@/components/icons'

interface ComplianceDocument {
  id: string
  document_type: string
  document_url: string
  document_name: string
  status: string
  generated_at: string
}

interface ComplianceDocumentsProps {
  documents: ComplianceDocument[]
  orderId: string
}

export function ComplianceDocuments({ documents, orderId }: ComplianceDocumentsProps) {
  const formatDate = (dateString: string) => {
    const date = new Date(dateString)
    return date.toLocaleDateString('en-QA', {
      year: 'numeric',
      month: 'short',
      day: 'numeric',
      hour: '2-digit',
      minute: '2-digit',
    })
  }

  const getStatusBadge = (status: string) => {
    switch (status) {
      case 'Generated':
        return <Badge variant="default">Generated</Badge>
      case 'Pending':
        return <Badge variant="secondary">Pending</Badge>
      default:
        return <Badge variant="outline">{status}</Badge>
    }
  }

  const handleDownload = (document: ComplianceDocument) => {
    window.open(document.document_url, '_blank')
  }

  return (
    <Card className="w-full">
      <CardHeader>
        <CardTitle>Compliance Documents</CardTitle>
      </CardHeader>
      <CardContent className="space-y-4">
        {documents.length === 0 ? (
          <div className="text-center py-8">
            <DocumentIcon className="h-12 w-12 text-muted-foreground mx-auto mb-3" />
            <p className="text-sm text-muted-foreground">
              No compliance documents generated yet
            </p>
          </div>
        ) : (
          <div className="space-y-3">
            {documents.map((document) => (
              <div
                key={document.id}
                className="border rounded-lg p-4 hover:bg-muted/50 transition"
              >
                <div className="flex items-start justify-between gap-4">
                  <div className="flex items-start gap-3 flex-1">
                    <DocumentIcon className="h-6 w-6 text-muted-foreground mt-0.5 flex-shrink-0" />
                    <div className="flex-1">
                      <div className="flex items-center gap-2 mb-1">
                        <h3 className="font-semibold">{document.document_type}</h3>
                        {getStatusBadge(document.status)}
                      </div>
                      <p className="text-xs text-muted-foreground mb-2">
                        {document.document_name}
                      </p>
                      <p className="text-xs text-muted-foreground">
                        Generated: {formatDate(document.generated_at)}
                      </p>
                    </div>
                  </div>
                  <Button
                    variant="outline"
                    size="sm"
                    onClick={() => handleDownload(document)}
                  >
                    Download
                  </Button>
                </div>
              </div>
            ))}
          </div>
        )}

        {/* Document Information */}
        {documents.length > 0 && (
          <div className="bg-muted p-4 rounded-lg mt-4">
            <h4 className="font-semibold mb-2">Document Information</h4>
            <ul className="text-sm text-muted-foreground space-y-1">
              <li>All documents are generated by the Compliance Engine</li>
              <li>Customs Declaration includes vehicle details and import information</li>
              <li>Documents are stored securely in cloud storage</li>
              <li>Required for vehicle registration in Qatar</li>
            </ul>
          </div>
        )}
      </CardContent>
    </Card>
  )
}
